feat: pre-commit docs and config on root folder

diff --git a/.github/disabled_workflows/enforce-branch-name.yml b/.github/disabled_workflows/enforce-branch-name.yml
--- a/.github/disabled_workflows/enforce-branch-name.yml
+++ b/.github/disabled_workflows/enforce-branch-name.yml
@@ -3,7 +3,7 @@ name: Enforce Branch Naming
 on:
   create:
     branches:
-      - '*'
+      - "*"
 
 jobs:
   enforce-branch-naming:
@@ -11,21 +11,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Check branch name format
-      id: check_branch
-      run: |
-        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
-        if [[ ! "$branch_name" =~ (^(feat|fix|refactor|docs|chore|test|style|build|ci|perf|revert)\/.*)|(master\-.*)|(dependabot\-.*) ]]; then
-          echo "Branch name doesn't match the required format."
-          exit 1
-        fi
+      - name: Check branch name format
+        id: check_branch
+        run: |
+          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
+          if [[ ! "$branch_name" =~ (^(feat|fix|refactor|docs|chore|test|style|build|ci|perf|revert)\/.*)|(master\-.*)|(dependabot\-.*) ]]; then
+            echo "Branch name doesn't match the required format."
+            exit 1
+          fi
 
-    - name: Delete branch if fail
-      if: ${{ failure() }}
-      uses: dawidd6/action-delete-branch@v3
-      with:
-        github_token: ${{github.token}}
-        branches: ${{ github.ref_name }}
+      - name: Delete branch if fail
+        if: ${{ failure() }}
+        uses: dawidd6/action-delete-branch@v3
+        with:
+          github_token: ${{github.token}}
+          branches: ${{ github.ref_name }}
